### ISSUE TITLE
Failed to resolve twitter SDK

### ISSUE THREAD

**Issue by yelamansa** [maksim88/EasyLogin#2]
When I try it  add to project, I have got Error 

`Error:Failed to resolve: com.twitter.sdk.android:twitter:2.3.2`

**Comment by mrhammadasif** [comment]
I fixed this by adding this repository in build.gradle file

`maven { url 'https://maven.fabric.io/public' }`

**Comment by maksim88** [comment]
Yeah you are right, for now you have to include that too.
I'll add it to the docs.
(For a later release i'll try to figure out another solution)
