### ISSUE TITLE
custom Button

### ISSUE THREAD

**Issue by ziacto** [maksim88/EasyLogin#7]
Hello Mak,

I want to use my own custom made button. how i can use without using your social button. if there is not option at least how i can update the text in your button.

**Comment by maksim88** [comment]
Hey,

there is no straightforward way to customize the texts. I found that it is possible to edit the login / logout button text on facebook by changing the `com_facebook_login_text` and `com_facebook_logout_text` properties.
So you can edit them the following way:

```
    <com.facebook.login.widget.LoginButton
        android:id="@+id/facebook_login_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="30dp"
        app:com_facebook_login_text="Custom login Text"
        app:com_facebook_logout_text="Custom logout Text"
        android:layout_marginBottom="30dp" />
```
the app namespace is bound to `http://schemas.android.com/apk/res-auto` in this case. 
As this is not a supported attribute the behaviour might break for the facebook button.


The gPlus button can be easily customizable. You can just create your own Button and then set it with setSignInButton() (I changed the dxpected type in the library for that, so this will be possible in the `0.5` release)

The text for the Twitter button can also be easily customizable with `setText()` on the button. 

But beware that you will have to supply your own translations for all the texts if you use one of those approaches above.
