### ISSUE TITLE
Social network with id = FACEBOOK already exists

### ISSUE THREAD

**Issue by MoliByte** [maksim88/EasyLogin#9]
EasyLogin.initialize();
easyLogin = EasyLogin.getInstance();

List<String> fbScope = Arrays.asList("public_profile", "email");

// error occurs on this line
easyLogin.addSocialNetwork(new FacebookNetwork(this, fbScope));

What should I do to avoid this Exception?

**Comment by maksim88** [comment]
This exception is only thrown when you call addSocialNetwork() and the network already exists.
Are you sure that you did not call addSocialNetwork() before the snippet you posted?

**Comment by hynra** [comment]
try this : 
```java
ArrayList<String> connectedNetwork = new ArrayList<>();
for (SocialNetwork socialNetwork : easyLogin.getInitializedSocialNetworks()) {
  Log.i("Social Login", socialNetwork.getNetwork().name());
  connectedNetwork.add(socialNetwork.getNetwork().name());
}
        
if(!connectedNetwork.contains("FACEBOOK"))
  easyLogin.addSocialNetwork(new FacebookNetwork(this, fbScope));
if(!connectedNetwork.contains("GOOGLE_PLUS"))
  easyLogin.addSocialNetwork(new GooglePlusNetwork(this));
```

**Comment by MoliByte** [comment]
@maksim88  this error occurs when i click login button second times ,it happens

**Comment by MoliByte** [comment]
@hynra here is a solution
